name: Just Vegan Vite

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies 🔰
        run: npm i
      - name: Run Build 🛠
        run: npm run build
        env:
          CI: false

      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1" # optional: defaults to us-east-1
          SOURCE_DIR: "dist" # optional: defaults to entire repository

        # Invalidate Cloudfront
      - name: Cloudfront Invalidation
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: "/*"
          AWS_REGION: "ap-south-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     env:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_DEFAULT_REGION: 'ap-south-1'
#     steps:
#         - uses: actions/checkout@v1

#         - name: Install dependencies 🔰
#           run: npm i

#         - name: Build
#           run: npm run build

#         - name: Deploy
#           uses: lbertenasco/s3-deploy@v1
#           with:
#             folder: dist
#             bucket: ${{ secrets.AWS_S3_BUCKET }}
#             dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
#             invalidation: / *
