name: Just Vegan Vite

on:
 push:
  branches:
    - master

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'ap-south-1'
    steps:
        - uses: actions/checkout@v1

        - name: Install dependencies 🔰
          run: yarn

        - name: Build
          run: yarn build

        - name: Deploy
          uses: lbertenasco/s3-deploy@v1
          with:
            folder: build
            bucket: ${{ secrets.AWS_S3_BUCKET }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: / *

# jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@master
#    - name: Install Dependencies 🔰
#      run: npm i
#    - name: Run Build 🛠   
#      run: npm run build
#      env:
#       CI: false
#    - uses: jakejarvis/s3-sync-action@master
#      with:
#        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
#      env:
#         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: 'ap-south-1' # optional: defaults to us-east-1
#         SOURCE_DIR: 'dist' # optional: defaults to entire repository  